import torch

from pxr import Sdf

from isaaclab.managers import SceneEntityCfg
from isaaclab.sim import get_current_stage
from soarm101_lab.utils.episode_randomizer import EpisodeRandomState, EpisodeRandomizer


def apply_episode_randomization(
    env,
    env_ids: torch.Tensor | None,
    random_state: EpisodeRandomState,
    cube_red_cfg: SceneEntityCfg,
    cube_green_cfg: SceneEntityCfg,
    cube_blue_cfg: SceneEntityCfg,
    asset_cfg: SceneEntityCfg,
    robot_asset: str = "robot",
):
    """
    Apply one EpisodeRandomState to the environment.

    This function DOES NOT generate random values.
    It simply applies the values already generated by EpisodeRandomizer.
    """

    if random_state is None:
        random_state = EpisodeRandomizer().sample()

    
    robot = env.scene[robot_asset]

    if env_ids is None:
        env_ids = torch.arange(env.num_envs, device=robot.device)

    print(
        f"🎲 APPLY_EPISODE_RANDOMIZATION CALLED | env_ids={env_ids}",
        flush=True,
    )
    #################################################
    # Cube Position
    #################################################

    cube_cfgs = {
        "cube_red": cube_red_cfg,
        "cube_green": cube_green_cfg,
        "cube_blue": cube_blue_cfg,
    }

    for cube_name, cube_cfg in cube_cfgs.items():

        cube = env.scene[cube_cfg.name]

        cube_pos = random_state.cube_positions[cube_name]

        positions = (
            torch.tensor(
                cube_pos,
                dtype=torch.float32,
                device=cube.device,
            )
            .unsqueeze(0)
            .repeat(len(env_ids), 1)
        )

        orientations = torch.zeros((len(env_ids), 4), device=cube.device)
        orientations[:, -1] = 1.0

        pose = torch.cat([positions, orientations], dim=-1)
        cube.write_root_pose_to_sim(pose,env_ids=env_ids)

        zero_velocity = torch.zeros((len(env_ids), 6), device=cube.device)
        cube.write_root_velocity_to_sim(zero_velocity, env_ids=env_ids)

    #################################################
    # Dome Light
    #################################################

    light = env.scene[asset_cfg.name]

    stage = get_current_stage()

    prim_path = light.prim_paths[0]

    with Sdf.ChangeBlock():
        prim = stage.GetPrimAtPath(prim_path)

        if prim.IsValid():
            prim.GetAttribute("inputs:exposure").Set(float(random_state.light_exposure))

    #################################################
    # Robot Initial Joint
    #################################################

    q = torch.zeros(
        (len(env_ids), robot.num_joints),
        device=robot.device,
    )

    for idx, joint_name in enumerate(robot.joint_names):

        q[:, idx] = random_state.joint_positions[joint_name]

    qd = torch.zeros_like(q)

    robot.write_joint_state_to_sim(
        q,
        qd,
        env_ids=env_ids,
    )